sonar.projectKey=arediss_Oscarr
sonar.organization=arediss

sonar.sources=packages/backend/src,packages/frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/data/**,**/*.test.*,**/*.spec.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=packages/backend/tsconfig.json,packages/frontend/tsconfig.json
